# Generated by Django 3.0.4 on 2020-03-14 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='broadcast_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
