# Generated by Django 3.0.4 on 2020-03-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_auto_20200314_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('DATA', 'Data')], default='TEXT', max_length=5),
        ),
    ]
